name: Update Script

permissions:
  contents: write

on:

  schedule:
    - cron: '0 10 * * *'  
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
  workflow_dispatch:  
jobs:
  update:
    #runs-on: ubuntu-latest
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt
        #run: |
        #  pip install torch
        #  pip install numpy
        #  pip install pandas
        #  pip install yfinance
        #  pip install scikit-learn
        #  pip install matplotlib
            

      - name: Run LSTM Model
        run: python lstm.py 
      
      - name: CSV2MD
        run: python utils/csv2md.py result/result.csv result/result.md
      - name: CSV2PNG
        run: python utils/csv2png.py result/result.csv result/table.png


      - name: Commit Changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in the repository."
            git config core.ignorecase false
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Updated at $(date '+%m-%d-%Y %H:%M:%S')"
            git push
          else
            echo "No changes detected in the repository."
          fi
      


      
      
      